version: '3.8'

services:
  db:
    image: postgres:15
    container_name: lpo_postgres
    environment:
      POSTGRES_DB: spad
      POSTGRES_USER: spad_user
      POSTGRES_PASSWORD: spad_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spad-net

  api:
    build: ./api-caderno-lpo
    container_name: lpo_api
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - spad-net

volumes:
  postgres_data:

networks:
  spad-net:
